name: Deploy React

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "${{ secrets.MAIN_ENV_FILE }}" > .env
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "${{ secrets.DEV_ENV_FILE }}" > .env
          else
            echo "Branch not configured for .env creation."
            exit 1
          fi

  set_up:
    uses: ./.github/workflows/setup_scp.yml
    secrets: inherit

  deploy:
    needs : [build , set_up] 
    runs-on: ubuntu-latest
    steps:
      - name : print
        run : echo ${{needs.set_up.outputs.host }} 
    
      - name: Deploy with scp-action
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.set_up.outputs.host }}
          username: ${{ needs.set_up.outputs.username }}
          key_path : 'id_rsa'
          source: "./README.md"
          target: "/var/www/vin_test"

          
  
