name: Deploy React

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "${{ secrets.MAIN_ENV_FILE }}" > .env
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "${{ secrets.DEV_ENV_FILE }}" > .env
          else
            echo "Branch not configured for .env creation."
            exit 1
          fi

      - name: Set scp deployment variables
        run: |
          mkdir -p ~/.ssh
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "host=${{ secrets.MAIN_SCP_CONFIG_HOST }}" >> $GITHUB_ENV
            echo "username=${{ secrets.MAIN_SCP_CONFIG_USERNAME }}" >> $GITHUB_ENV
            echo "${{ secrets.MAIN_SCP_CONFIG_KEY }}" > id_rsa
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "host=${{ secrets.DEV_SCP_CONFIG_HOST }}" >> $GITHUB_ENV
            echo "username=${{ secrets.DEV_SCP_CONFIG_USERNAME }}" >> $GITHUB_ENV
            echo "${{ secrets.DEV_SCP_CONFIG_KEY }}" > id_rsa
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
          chmod 644 id_rsa

      - name: Deploy with scp-action
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.host }}
          username: ${{ env.username }}
          key_path : 'id_rsa'
          source: "./README.md"
          target: "/var/www/vin_test"

          
  
