name: Deploy React

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Log .env file contents (for debugging)
        run: |
          echo "Logging .env Key:"
          awk -F= '{print $1}' .env


          
  
