name: Setup SCP Variable

on:
  workflow_call: 
    outputs:
        host:
          description: "SCP Host"
          value: ${{ jobs.set_up.outputs.output1  }}
        username:
          description: "SCP Username"
          value: ${{ jobs.set_up.outputs.output2 }}
jobs:
  set_up:
    name: Generate variable
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.host }}
      output2: ${{ steps.step1.outputs.username }}
    steps:
      - id: step1
        run: |
          mkdir -p ~/.ssh
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "host=hello" >> "$GITHUB_OUTPUT"
            echo "username=${{ secrets.MAIN_SCP_CONFIG_USERNAME }}" >> "$GITHUB_OUTPUT"
            echo "${{ secrets.MAIN_SCP_CONFIG_KEY }}" > id_rsa
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "host=${{ secrets.DEV_SCP_CONFIG_HOST }}" >> "$GITHUB_OUTPUT"
            echo "username=${{ secrets.DEV_SCP_CONFIG_USERNAME }}" >> "$GITHUB_OUTPUT"
            echo "${{ secrets.DEV_SCP_CONFIG_KEY }}" > id_rsa
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
          chmod 644 id_rsa
